#!/bin/bash
# Ambil nilai-nilai ini dari Railway dashboard → Variables
# Jalankan: bash fly-set-secrets.sh

APP_NAME="qc-backend"

fly secrets set \
  SECRET_KEY="GANTI_DENGAN_SECRET_KEY_DARI_RAILWAY" \
  APP_NAME="Content Ops" \
  VAPID_PUBLIC_KEY="GANTI_DENGAN_VAPID_PUBLIC_KEY_DARI_RAILWAY" \
  VAPID_PRIVATE_KEY="GANTI_DENGAN_VAPID_PRIVATE_KEY_DARI_RAILWAY" \
  VAPID_MAILTO="content@vplushort.com" \
  GOOGLE_SPREADSHEET_ID="GANTI_DENGAN_SPREADSHEET_ID_DARI_RAILWAY" \
  GOOGLE_CLIENT_ID="GANTI_DENGAN_GOOGLE_CLIENT_ID_DARI_RAILWAY" \
  GOOGLE_CLIENT_SECRET="GANTI_DENGAN_GOOGLE_CLIENT_SECRET_DARI_RAILWAY" \
  GOOGLE_REFRESH_TOKEN="GANTI_DENGAN_GOOGLE_REFRESH_TOKEN_DARI_RAILWAY" \
  --app $APP_NAME

echo "✅ Secrets set. Sekarang deploy:"
echo "   fly deploy --app $APP_NAME"
